require 'rails_ext/active_record/sti_instantiation'
require 'rails_ext/active_record/sticky_changes'
require 'rails_ext/action_controller/event_helper'
require 'rails_ext/action_controller/page_caching'
require 'rails_ext/action_controller/render_with_custom_templates'
require 'rails_ext/railties/configurable_plugins'
