#!/usr/bin/env ruby

require "fileutils"

def rails_root
  @rails_root ||= File.expand_path(File.dirname(__FILE__) + '/../../..')
end

def patch_file(path, current, insert, options = {})
  options = {
    :patch_mode => :insert_after
  }.merge(options)

  old_text = current
  new_text = patch_string(current, insert, options[:patch_mode])

  content = File.open(path) { |f| f.read }
  content.gsub!(old_text, new_text) unless content =~ /#{Regexp.escape(insert)}/mi
  File.open(path, 'w') { |f| f.write(content) }
end

def patch_string(current, insert, mode = :insert_after)
  case mode
  when :change
    "#{insert}"
  when :insert_after
    "#{current}\n#{insert}"
  when :insert_before
    "#{insert}\n#{current}"
  else
    patch_string(current, insert, :insert_after)
  end
end

def backup(relative_file_path)
  file_path = rails_root + relative_file_path
  FileUtils.mv(file_path, file_path + ".backup-#{Time.now.strftime("%Y.%m.%d-%H.%M.%S")}") if File.exist?(file_path)
end

def copy_with_backup(from_relative_path, to_relative_path)
  backup(to_relative_path)
  FileUtils.cp(rails_root + from_relative_path, rails_root + to_relative_path)
end

File.unlink rails_root + '/public/index.html' rescue Errno::ENOENT

patch_file rails_root + '/config/environment.rb',
           "require File.join(File.dirname(__FILE__), 'boot')",
           "require File.join(File.dirname(__FILE__), '../vendor/adva/engines/adva_cms/boot')"

# copy_with_backup "/vendor/adva/engines/adva_cms/config/initializers/adva_cms.rb", 
#                  "/config/initializers/adva_cms.rb"

patch_file 'config/initializers/new_rails_defaults.rb',
  "ActionController::Routing.generate_best_match = false",
  "ActionController::Routing.generate_best_match = true",
  :patch_mode => :change

patch_file 'config/initializers/new_rails_defaults.rb',
  "ActionController::Routing.generate_best_match = true",
  "# You *must* use Rails' old routing recognition/generation mode in order for adva-cms to work correctly
#ActionController::Routing.generate_best_match = false",
  :patch_mode => :insert_before

File.open(rails_root + '/script/test-adva', "w") do |f|
  f << "#!/usr/bin/env ruby\n"
  f << "paths = ARGV.clone\n"
  f << "load 'vendor/adva/script/test'\n"
end

puts <<END

  Welcome to Adva-cms!

  Adva-cms is a cutting edge open source application platform
  based on Ruby on Rails and Rails Engines.

  Before start, please copy assets and run migrations:

  rake adva:assets:install     # symlinks plugin assets to public/
  rake db:migrate              # copies engine migrations to app, does usual migration and removes
                               # engine migrations after it's done

  ruby script/server
  open http://localhost:3000

  You should see adva-cms installation screen.
  Fill out the form and you're started, enjoy!

  Please read more info from README and /doc directory.

  Adva-cms team

END
